services:
  app:
    image: futrime/lipindex:latest
    depends_on:
      - postgres
    environment:
      GITHUB_BOT_TOKEN:
      NODE_ENV: production
    links:
      - postgres
    ports:
      - 127.0.0.1:11400:11400
    restart: always
  
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
