on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - apps/**
  push:
    paths:
      - .github/workflows/build.yml
      - apps/**
  workflow_dispatch:

jobs:
  check-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - api
          - github-bot
          - pypi-bot
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          npm i -g ts-standard

      - run: |
          ts-standard ./**/*.ts
        working-directory: ./apps/${{ matrix.app }}

  build-docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - api
          - github-bot
          - pypi-bot
    steps:
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ./apps/${{ matrix.app }}
