on:
  release:
    types: 
      - published

env:
  VERSION: 0.0.0

jobs:
  publish-docker-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Trim prefix v from version string
        run: |
          echo "VERSION=${{ github.ref_name }}" | sed 's/=v/=/' >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker image (prerelease)
        uses: docker/build-push-action@v4
        if: ${{ github.event.release.prerelease }}
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ghcr.io/lippkg/lipindex:${{ env.VERSION }}

      - name: Publish Docker image (release)
        uses: docker/build-push-action@v4
        if: ${{ !github.event.release.prerelease }}
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ghcr.io/lippkg/lipindex:${{ env.VERSION }}
            ghcr.io/lippkg/lipindex:latest
